-- Seed: 12 ademwerk-niveaus rond Breathe With Sandy (C0).
-- config = player-config per mode; unlock = ontgrendel-regels; media = video/audio.

insert into public.breath_levels
  (level, slug, name, one_liner, track, mode, setup, execution, breathing,
   mistakes, prescription, config, unlock, needs_safety_ack, media, xp, sort)
values
(1, 'neus_middenrif', 'Neus- & middenrifademhaling',
 'Verstil je basisademhaling: door de neus, laag in de buik, langzaam.',
 'kalmerend', 'paced',
 array['Zit rechtop of lig op je rug.','Eén hand op je buik, één op je borst.'],
 array['Adem uitsluitend door je neus.','De onderste hand (buik) beweegt, de bovenste (borst) blijft stil.','Zachte inademing, iets langere ontspannen uitademing.'],
 '~4 tellen in, ~6 tellen uit — ongeveer 6 ademhalingen per minuut.',
 array['Ademen in de borst i.p.v. de buik.','Forceren of te snel gaan.'],
 '5 minuten · dagelijks',
 '{"phases":[{"label":"Adem in","secs":4,"scale":1.0},{"label":"Adem uit","secs":6,"scale":0.45}],"durationMin":5}'::jsonb,
 '{"requires":[]}'::jsonb, false,
 '{"provider":"youtube","url":"https://www.youtube.com/watch?v=VIs2f8Eq7nQ","title":"Sandy — Simplest Breathwork to Release Stress (5m)"}'::jsonb, 25, 1),

(2, 'bolt_meting', 'Adembewustzijn & je CO₂-nulmeting',
 'Meet waar je staat — je Control Pause (BOLT) — en leer je ademdrang herkennen.',
 'kalmerend', 'bolt',
 array['Zit ontspannen.','Doe eerst 2 minuten rustige neusademhaling.'],
 array['Na een NORMALE uitademing: neus dicht en de timer start.','Stop bij de EERSTE duidelijke ademdrang (niet je maximale hold).','Adem daarna rustig verder door je neus.'],
 'De meting stopt bij de eerste drang — het is geen wedstrijd.',
 array['Doorgaan tot je maximum (dat is niet de bedoeling).','Staand of vlak na inspanning meten.'],
 'Meet 3-4× per week; je getal opent later de zware niveaus.',
 '{}'::jsonb,
 '{"requires":[{"type":"sessions","level":1,"count":5}]}'::jsonb, false,
 '{"provider":"link","url":"https://oxygenadvantage.com/","title":"Oxygen Advantage — BOLT uitleg"}'::jsonb, 25, 2),

(3, 'vier_zeven_acht', 'Verlengde uitademing · 4-7-8',
 'Rem je zenuwstelsel af via een lange uitademing — de ontspanningsademhaling.',
 'kalmerend', 'paced',
 array['Zit rechtop.','Tongpunt tegen je verhemelte, net achter de boventanden.'],
 array['Adem geruisloos in door de neus (4).','Houd vast (7).','Adem volledig uit door de mond met een zachte "whoosh" (8).'],
 'Verhouding 4-7-8; de tellen tellen, niet de absolute seconden.',
 array['De uitademing niet volledig maken.','Bij duizeligheid doorgaan — blijf zitten.'],
 '4 cycli · 1-2× per dag',
 '{"phases":[{"label":"Adem in","secs":4,"scale":1.0},{"label":"Vasthouden","secs":7,"scale":1.0},{"label":"Adem uit","secs":8,"scale":0.4}],"cycles":4}'::jsonb,
 '{"requires":[{"type":"bolt_count","count":3}]}'::jsonb, false,
 '{"provider":"youtube","url":"https://www.youtube.com/watch?v=8mTPLwEE9vU","title":"Sandy — 10m Morning Breathwork Without Anxiety"}'::jsonb, 25, 3),

(4, 'box_breathing', 'Box breathing · 4-4-4-4',
 'Vierkante ademhaling voor kalme focus onder druk.',
 'kalmerend', 'paced',
 array['Zit rechtop, schouders los.'],
 array['In (4) → vast vol (4) → uit (4) → vast leeg (4).','Adem laag in de buik, keel ontspannen.'],
 'Vier gelijke zijden; pas de lengte aan je CO₂-tolerantie aan.',
 array['De lege-long-hold te lang maken bij spanning.'],
 '4 minuten · dagelijks',
 '{"phases":[{"label":"Adem in","secs":4,"scale":1.0},{"label":"Vast — vol","secs":4,"scale":1.0},{"label":"Adem uit","secs":4,"scale":0.45},{"label":"Vast — leeg","secs":4,"scale":0.45}],"durationMin":4}'::jsonb,
 '{"requires":[{"type":"sessions","level":3,"count":5}]}'::jsonb, false,
 '{"provider":"youtube","url":"https://www.youtube.com/watch?v=4aYaIINUgck","title":"Sandy — Chill Out in 5 Minutes (Box Breathing)"}'::jsonb, 25, 4),

(5, 'coherent', 'Coherente ademhaling · ~5,5/min',
 'Breng hart, longen en bloeddruk in resonantie — maximale rust.',
 'kalmerend', 'paced',
 array['Zit of lig ontspannen.'],
 array['Gelijke in- en uitademing door de neus, zonder pauze.','Zacht en golvend.'],
 '5,5 seconden in, 5,5 seconden uit (~5,5 per minuut).',
 array['Forceren; het mag heel zacht.'],
 '10 minuten · dagelijks · telt mee voor de zware niveaus',
 '{"phases":[{"label":"Adem in","secs":5.5,"scale":1.0},{"label":"Adem uit","secs":5.5,"scale":0.45}],"durationMin":10}'::jsonb,
 '{"requires":[{"type":"sessions","level":4,"count":5}]}'::jsonb, false,
 '{"provider":"youtube","url":"https://www.youtube.com/watch?v=NutFAFeEfoM","title":"Sandy — 10 Minute Nervous System Reset"}'::jsonb, 25, 5),

(6, 'physiological_sigh', 'Physiological sigh · cyclisch zuchten',
 'De snelste noodrem tegen acute stress; als 5-min-praktijk stemmingsverhogend.',
 'kalmerend', 'paced',
 array['Wil dan ook — zit, sta of lig.'],
 array['Dubbele inademing door de neus (grote teug + korte toef erbovenop).','Lange, volledige uitademing door de mond.'],
 'Twee inademingen, dan alles rustig eruit.',
 array['De tweede kleine inademing overslaan.'],
 '1-3 zuchten (acuut) of 5 minuten (dagelijks)',
 '{"phases":[{"label":"Adem in","secs":2,"scale":0.9},{"label":"Nog een teugje","secs":1,"scale":1.1},{"label":"Lange uitademing","secs":6,"scale":0.35}],"durationMin":5}'::jsonb,
 '{"requires":[{"type":"sessions","level":5,"count":5}]}'::jsonb, false,
 '{"provider":"link","url":"https://www.hubermanlab.com/newsletter/breathwork-protocols-for-health-focus-stress","title":"Huberman — Breathwork Protocols"}'::jsonb, 25, 6),

(7, 'nadi_shodhana', 'Nadi shodhana · wisselend neusgat',
 'Wisselende neusgat-ademhaling voor balans, focus en rust.',
 'kalmerend', 'paced',
 array['Zit rechtop.','Duim op je rechterneusgat, ringvinger op je linker.'],
 array['Sluit rechts → in door links.','Sluit links → uit + in door rechts.','Sluit rechts → uit door links. Dat is één ronde.'],
 'Zacht en gelijkmatig, helemaal door de neus.',
 array['Forceren; overslaan bij een verstopte neus.'],
 '10 minuten · dagelijks of om de dag',
 '{"phases":[{"label":"In door links","secs":4,"scale":1.0},{"label":"Uit door rechts","secs":4,"scale":0.45},{"label":"In door rechts","secs":4,"scale":1.0},{"label":"Uit door links","secs":4,"scale":0.45}],"durationMin":10}'::jsonb,
 '{"requires":[{"type":"sessions","level":6,"count":3}]}'::jsonb, false,
 '{"provider":"link","url":"https://www.breathewithsandy.com/online-program","title":"Sandy — Pranayama-programma"}'::jsonb, 25, 7),

(8, 'buteyko', 'Buteyko · CO₂-tolerantie opbouwen',
 'Train een lichter ademvolume en verhoog je Control Pause — de brug naar de zware niveaus.',
 'brug', 'paced',
 array['Zit rechtop, ontspannen.'],
 array['Maak je neusademhaling bewust kleiner en zachter dan normaal.','Zoek een MILDE, comfortabele luchthonger — die blijft draaglijk.'],
 'Licht ademtekort: net iets te weinig lucht, nooit naar lucht happen.',
 array['Te veel ademtekort opzoeken.','Meet wekelijks opnieuw je BOLT.'],
 '10 minuten · 4-6× per week + wekelijkse BOLT',
 '{"phases":[{"label":"Zacht in","secs":3,"scale":0.8},{"label":"Zacht uit","secs":4,"scale":0.5}],"durationMin":10}'::jsonb,
 '{"requires":[{"type":"sessions","level":7,"count":5}]}'::jsonb, false,
 '{"provider":"link","url":"https://oxygenadvantage.com/","title":"Oxygen Advantage — licht ademtekort"}'::jsonb, 25, 8),

(9, 'ademhoud', 'Ademhoud-progressie · breath holds',
 'Gestructureerde ademhoudingen om je ademdrang geleidelijk te vergroten.',
 'zwaar', 'rounds',
 array['ALTIJD zittend of liggend, op het droge. Nooit in of bij water.'],
 array['Rustige breathe-up van een minuut.','Na een normale uitademing: houd vast tot een comfortabele drang.','Tik zodra je wilt ademen; herstel, en begin de volgende ronde.'],
 'Nooit hyperventileren vóór een hold — dat maskeert de ademdrang.',
 array['Hyperventileren vóór de hold.','In/bij water of tijdens bewegen.'],
 '6 ronden · 3-4× per week · nooit bij water',
 '{"activeSec":60,"rounds":6,"retention":true,"recoveryHoldSec":0,"activePhases":[{"label":"Rustig in","secs":4,"scale":0.9},{"label":"Rustig uit","secs":4,"scale":0.5}]}'::jsonb,
 '{"requires":[{"type":"bolt_min","min":20},{"type":"sessions","level":8,"count":8}]}'::jsonb, true,
 '{"provider":"link","url":"https://breathhold.co/resources/how-to-train-co2-tolerance","title":"CO₂-tolerantie training"}'::jsonb, 25, 9),

(10, 'sandy_transform_instap', 'Sandy · transformationeel (instap)',
 'Sandy''s signatuur: ronden verbonden ademhaling op muziek + retentie — activerend, ontladend.',
 'zwaar', 'follow',
 array['Lig op je rug, koptelefoon op, warme ruimte, dekentje bij de hand.'],
 array['Volg Sandy''s muziek: actieve, verbonden ademhaling zonder pauze (meestal door de mond).','Adem in de buik en dan de borst; losgelaten uitademing.','Op haar cue: retentie, dan een herstel-inademing. Dat is één ronde.'],
 'De beat van de muziek stuurt je tempo en diepte.',
 array['Tintelingen/tetanie zijn normaal — vertraag als het te veel wordt.'],
 '3 ronden · ~15 minuten · liggend',
 '{"rounds":3}'::jsonb,
 '{"requires":[{"type":"bolt_min","min":20},{"type":"sessions","level":5,"count":10}]}'::jsonb, true,
 '{"provider":"youtube","url":"https://www.youtube.com/watch?v=O4d7u7SikyA","title":"Sandy — Release Stuck Energy & Emotions (15m, 3 Rounds)"}'::jsonb, 25, 10),

(11, 'wim_hof', 'Wim Hof-methode · power breaths + retentie',
 'Cyclische krachtige ademhaling + retentie voor energie, alertheid en stressweerbaarheid.',
 'zwaar', 'rounds',
 array['Zittend of liggend op een veilige plek. Nooit staand, bij water of rijdend.'],
 array['30-40 power breaths: vol in, losjes uit, in een vlot ritme.','Na de laatste uitademing: houd leeg vast zolang comfortabel.','Bij de drang: grote herstel-inademing, ~15s vasthouden. Dat is één ronde.'],
 'Tintelingen en tetanie ("klauwhand") zijn normaal en verdwijnen vanzelf.',
 array['In/bij water of tijdens rijden.','Combineren met koud water op hetzelfde moment.'],
 '30-40 breaths × 3-4 ronden · 1× per dag',
 '{"activeBreaths":30,"rounds":3,"retention":true,"recoveryHoldSec":15,"activePhases":[{"label":"Vol in","secs":1.6,"scale":1.0},{"label":"Los uit","secs":1.4,"scale":0.55}]}'::jsonb,
 '{"requires":[{"type":"sessions","level":10,"count":5},{"type":"bolt_min","min":20}]}'::jsonb, true,
 '{"provider":"youtube","url":"https://www.youtube.com/watch?v=tybOi4hjZFQ","title":"Wim Hof — Guided Breathing"}'::jsonb, 25, 11),

(12, 'sandy_journey', 'Sandy · diepe journey (zwaarst)',
 'Lange, doorlopende verbonden ademhaling op muziek met meerdere retentie-ronden.',
 'zwaar', 'follow',
 array['Lig op je rug, koptelefoon op, warme ruimte, ogen dicht, dekentje bij de hand.'],
 array['Continue, circulaire ademhaling zonder pauze op Sandy''s beat.','Meerdere ronden met retenties, gevolgd door stille integratie.','Bouw de duur pas op na meerdere comfortabele sessies.'],
 'Doe de lange journeys bij voorkeur onder begeleiding, zeker de eerste keren.',
 array['Solo de eerste keren; bij overweldiging vertragen en door de neus ademen.'],
 '30 minuten, 4 ronden · liggend · liefst met begeleiding',
 '{"rounds":4}'::jsonb,
 '{"requires":[{"type":"bolt_min","min":20},{"type":"sessions","level":5,"count":10},{"type":"sessions","level":10,"count":5}]}'::jsonb, true,
 '{"provider":"link","url":"https://www.patreon.com/posts/30-minute-i-4-129173163","title":"Sandy — 30m Gratitude Breathwork, 4 Rounds (Patreon)"}'::jsonb, 25, 12);
