-- Ademwerk video-first herstructurering.
--
-- De coaching-tekst beschrijft nu de ÉCHTE video's van Breathe With Sandy en de
-- niveaus lopen op in zwaarte precies zoals haar video's zelf: van korte
-- kalmerende technieken (5 min) via zenuwstelsel-resets (10-12 min) en de
-- eerste verbonden-ademhaling-ronden naar haar signatuur release-journeys
-- (15/20/30 min) en de diepste journeys (40/45 min).
--
-- De video is leidend: alle niveaus draaien in `follow`-modus (de video begeleidt
-- je volledig, de orb draait niet mee). Alle video-ID's zijn geverifieerd als
-- afkomstig van het kanaal @BreatheWithSandy. Gating is puur op beoefening
-- (X sessies van het vorige niveau) — geen BOLT-poort meer in de hoofdlijn.

delete from breath_levels;

insert into breath_levels
  (level, slug, name, one_liner, track, mode, setup, execution, breathing,
   mistakes, prescription, config, unlock, needs_safety_ack, media, xp, sort)
values
-- ── KALMEREND — het fundament (5 min, vaste technieken) ─────────────────────
(1, 'box_5min', 'Box breathing · 5 min met Sandy',
 'Sandy''s rustigste start: vier gelijke tellen in, vast, uit, vast.',
 'kalmerend', 'follow',
 ARRAY['Zit rechtop of lig comfortabel','Adem door de neus','Zet de video op en volg Sandy''s tempo']::text[],
 ARRAY['Sandy telt je door een vierkant: 4 tellen in','4 tellen vasthouden','4 tellen uit','4 tellen vasthouden — vijf minuten lang']::text[],
 '4 in · 4 vast · 4 uit · 4 vast, alles door de neus',
 ARRAY['Forceer de vasthoud-momenten niet; laat ze zacht zijn','Schouders laag houden']::text[],
 'Volg Sandy · 5 min · box breathing',
 '{"durationMin":5}'::jsonb, '{"requires":[]}'::jsonb, false,
 '{"provider":"youtube","url":"https://www.youtube.com/watch?v=4aYaIINUgck","title":"Sandy — Chill Out In 5 Minutes (Box Breathing)"}'::jsonb,
 25, 1),

(2, 'vier_zeven_acht', '4-7-8 · in slaap vallen',
 'De klassieke inslaap-ademhaling: kort in, lang vast, heel lang uit.',
 'kalmerend', 'follow',
 ARRAY['Lig of zit ontspannen','Tongpunt zacht achter je boventanden','Volg Sandy''s stem']::text[],
 ARRAY['Adem 4 tellen in door de neus','Houd 7 tellen vast','Blaas 8 tellen uit door de mond','Sandy herhaalt dit rustig — ideaal vlak voor het slapen']::text[],
 '4 in · 7 vast · 8 uit (mond), lange uitademing',
 ARRAY['Niet naar lucht happen — hou het zacht','Word je licht in het hoofd, adem dan gewoon normaal']::text[],
 'Volg Sandy · 5 min · 4-7-8',
 '{"durationMin":5}'::jsonb, '{"requires":[{"type":"sessions","level":1,"count":3}]}'::jsonb, false,
 '{"provider":"youtube","url":"https://www.youtube.com/watch?v=IumIKwyx8pg","title":"Sandy — 4-7-8 Calm Breathing (5 Min, Sleep)"}'::jsonb,
 25, 2),

(3, 'simpelste_stress', 'Simpelste stress-release',
 'Sandy''s eenvoudigste techniek om spanning los te laten in 5 minuten.',
 'kalmerend', 'follow',
 ARRAY['Zit of lig, ogen mogen dicht','Adem laag in je buik','Volg de video']::text[],
 ARRAY['Sandy brengt je naar een langzame neusademhaling','De uitademing wordt langer dan de inademing','Vijf minuten om spanning uit lijf en hoofd te laten zakken']::text[],
 'Langzaam door de neus, uitademing langer dan inademing',
 ARRAY['Geen prestatie — laat de adem eerder los dan dat je ''m stuurt']::text[],
 'Volg Sandy · 5 min · ontspanning',
 '{"durationMin":5}'::jsonb, '{"requires":[{"type":"sessions","level":2,"count":3}]}'::jsonb, false,
 '{"provider":"youtube","url":"https://www.youtube.com/watch?v=VIs2f8Eq7nQ","title":"Sandy — Simplest Breathwork to Release Stress (5 Min)"}'::jsonb,
 25, 3),

(4, 'ns_reset_5', 'Zenuwstelsel-reset · 5 min',
 'Een korte reset die je zenuwstelsel uit de stress-stand haalt.',
 'kalmerend', 'follow',
 ARRAY['Zit rechtop, voeten op de grond','Adem door de neus','Volg Sandy''s tempo']::text[],
 ARRAY['Sandy leidt je door rustige, gelijkmatige ademhalingen','Het tempo daalt geleidelijk','Na vijf minuten sta je merkbaar rustiger in je lijf']::text[],
 'Rustige neusademhaling, kalm en gelijkmatig',
 ARRAY['Niet dieper ademen dan prettig voelt']::text[],
 'Volg Sandy · 5 min · reset',
 '{"durationMin":5}'::jsonb, '{"requires":[{"type":"sessions","level":3,"count":3}]}'::jsonb, false,
 '{"provider":"youtube","url":"https://www.youtube.com/watch?v=ekKG8h8XakI","title":"Sandy — Reset Your Nervous System in 5 Minutes"}'::jsonb,
 25, 4),

-- ── BRUG — langere resets + eerste verbonden ademhaling (8-12 min) ───────────
(5, 'ns_reset_10', '10 min zenuwstelsel-reset',
 'Een langere paced reset — ochtend, middag of avond.',
 'brug', 'follow',
 ARRAY['Neem 10 minuten waarin je niet gestoord wordt','Zit of lig comfortabel','Volg Sandy']::text[],
 ARRAY['Sandy houdt een rustig, constant ritme aan','De langere duur laat je dieper zakken dan de 5-minuten-sessies','Ideaal als vast dagelijks ankermoment']::text[],
 'Traag, coherent ritme door de neus',
 ARRAY['Val je in slaap? Prima — dan had je lijf het nodig']::text[],
 'Volg Sandy · 10 min · reset',
 '{"durationMin":10}'::jsonb, '{"requires":[{"type":"sessions","level":4,"count":3}]}'::jsonb, false,
 '{"provider":"youtube","url":"https://www.youtube.com/watch?v=NutFAFeEfoM","title":"Sandy — 10 Minute Nervous System Reset"}'::jsonb,
 25, 5),

(6, 'ochtend_regulatie_12', '12 min complete ochtend-regulatie',
 'Sandy''s complete ochtendroutine om je zenuwstelsel elke dag te reguleren.',
 'brug', 'follow',
 ARRAY['Doe dit ''s ochtends, voor je dag begint','Zit rechtop','Volg de volledige routine']::text[],
 ARRAY['Sandy bouwt een complete routine op van rustige ademhaling','Twaalf minuten om gereguleerd de dag in te gaan','Legt de basis voor de zwaardere sessies verderop']::text[],
 'Opbouwende, rustige neusademhaling',
 ARRAY['Sla de opbouw niet over — de rust zit in het geleidelijke']::text[],
 'Volg Sandy · 12 min · ochtendregulatie',
 '{"durationMin":12}'::jsonb, '{"requires":[{"type":"sessions","level":5,"count":3}]}'::jsonb, false,
 '{"provider":"youtube","url":"https://www.youtube.com/watch?v=HSxLK_MkaDE","title":"Sandy — 12 Minute Complete Nervous System Routine"}'::jsonb,
 25, 6),

(7, 'connected_8_3', '8 min · 3 ronden energie',
 'Je eerste kennismaking met verbonden ademhaling — 3 korte, energieke ronden.',
 'brug', 'follow',
 ARRAY['Zit rechtop of lig','Dit is actiever: adem door de mond als Sandy dat vraagt','Zet je schrap voor lichte tinteling — dat is normaal']::text[],
 ARRAY['Sandy leidt je door 3 ronden actieve, verbonden ademhaling','Elke ronde bouwt energie op','Tussen de ronden kom je even tot rust','Kort en energiek — een zachte opstap naar de journeys']::text[],
 'Verbonden ademhaling (in en uit zonder pauze), actiever tempo',
 ARRAY['Tintelingen of duizeligheid zijn normaal; zak terug naar rustig ademen als het te veel wordt','Doe dit niet staand']::text[],
 'Volg Sandy · 8 min · 3 ronden',
 '{"durationMin":8}'::jsonb, '{"requires":[{"type":"sessions","level":6,"count":2}]}'::jsonb, true,
 '{"provider":"youtube","url":"https://www.youtube.com/watch?v=jYsRfi1JrSI","title":"Sandy — 8 Minute Breathing to Boost Energy (3 Rounds)"}'::jsonb,
 25, 7),

(8, 'connected_10_3_hold', '10 min · 3 ronden met ademhoud',
 'Verbonden ademhaling in 3 ronden, nu met een adempauze na elke ronde.',
 'brug', 'follow',
 ARRAY['Lig comfortabel op je rug','Volg de timer op het scherm','Na elke ronde houd je je adem in zo lang als comfortabel']::text[],
 ARRAY['3 ronden verbonden ademhaling met Sandy','Na elke ronde: adem uit en houd je adem in tot de eerste drang','De on-screen timer telt je door elke fase','Je eerste ervaring met retentie tussen de ronden']::text[],
 'Verbonden ademhaling + adempauze (retentie) na elke ronde',
 ARRAY['Forceer de adempauze niet — adem in zodra je lijf erom vraagt','Blijf liggen tijdens de holds']::text[],
 'Volg Sandy · 10 min · 3 ronden + holds',
 '{"durationMin":10}'::jsonb, '{"requires":[{"type":"sessions","level":7,"count":3}]}'::jsonb, true,
 '{"provider":"youtube","url":"https://www.youtube.com/watch?v=NNai0Cn8Bhs","title":"Sandy — 10 Minute Guided Breathing (3 Rounds, On-Screen Timer)"}'::jsonb,
 25, 8),

-- ── ZWAAR — Sandy''s signatuur release-journeys (oplopend) ───────────────────
(9, 'journey_15_stuck', 'Release stuck energy · 15 min journey',
 'Sandy''s signatuur-journey: 3 ronden verbonden ademhaling die vastzittende energie en emotie losmaken.',
 'zwaar', 'follow',
 ARRAY['Lig op je rug op een zachte ondergrond','Koptelefoon op voor de muziek','Zorg dat je 15 min ongestoord bent — er kan emotie loskomen']::text[],
 ARRAY['Intro rond 0:00 — Sandy legt uit en brengt je in positie','Ronde 1 vanaf ~1:30 · Ronde 2 vanaf ~4:45 · Ronde 3 vanaf ~8:51 — elke ronde intenser','Afsluitende meditatie vanaf ~13:39 in stilte','De ronden bouwen op; laat gaan wat naar boven komt']::text[],
 'Twee-delige verbonden ademhaling (buik, dan borst) zonder pauze, op muziek',
 ARRAY['Tintelingen, trillen of emotie zijn normaal en veilig — laat het er zijn','Nooit bij water of achter het stuur','Stop en adem normaal bij echt ongemak']::text[],
 'Volg Sandy · 15 min · 3 ronden',
 '{"durationMin":15}'::jsonb, '{"requires":[{"type":"sessions","level":8,"count":3}]}'::jsonb, true,
 '{"provider":"youtube","url":"https://www.youtube.com/watch?v=O4d7u7SikyA","title":"Sandy — Release Stuck Energy & Emotions (15 Min, 3 Rounds)"}'::jsonb,
 25, 9),

(10, 'journey_15_body', 'Release in het lichaam · 15 min',
 'Een tweede 15-minuten journey, meer somatisch: energie loslaten uit het lichaam.',
 'zwaar', 'follow',
 ARRAY['Lig comfortabel, koptelefoon op','15 min ongestoord','Deken bij de hand — je kunt het koud of warm krijgen']::text[],
 ARRAY['Verbonden ademhaling in ronden met Sandy','Focus ligt op fysieke ontlading — waar zit spanning vast?','Ademhoud-momenten verdiepen de ontlading','Eindigt in stille integratie']::text[],
 'Verbonden ademhaling op muziek, met retentie tussen de ronden',
 ARRAY['Laat het lichaam bewegen of trillen als het wil','Forceer niets; de adem doet het werk']::text[],
 'Volg Sandy · 15 min · somatisch',
 '{"durationMin":15}'::jsonb, '{"requires":[{"type":"sessions","level":9,"count":2}]}'::jsonb, true,
 '{"provider":"youtube","url":"https://www.youtube.com/watch?v=lUHmOLHKqew","title":"Sandy — Release Stuck Energy in the Body (15 Min)"}'::jsonb,
 25, 10),

(11, 'journey_20_trauma', 'Los spanning & trauma · 20 min',
 'Eén lange, doorlopende journey om opgeslagen stress en spanning uit het lijf te laten.',
 'zwaar', 'follow',
 ARRAY['Lig op je rug, warm en ongestoord, 20 min','Koptelefoon op','Zet iets te drinken klaar voor erna']::text[],
 ARRAY['Intro tot ~2:20 — Sandy bereidt je voor','Vanaf ~2:20 één lange, doorlopende verbonden ademhaling (geen losse ronden)','De continue ademhaling brengt je dieper dan de 15-min journeys','Verwacht sterke tinteling; laat emotie en spanning los']::text[],
 'Doorlopende verbonden ademhaling op muziek, ~18 min aaneengesloten',
 ARRAY['Krampgevoel in de handen (tetanie) is tijdelijk en onschuldig — ontspan en adem zachter','Doe dit liggend, nooit bij water','Kom rustig overeind na afloop']::text[],
 'Volg Sandy · 20 min · doorlopend',
 '{"durationMin":20}'::jsonb, '{"requires":[{"type":"sessions","level":10,"count":2}]}'::jsonb, true,
 '{"provider":"youtube","url":"https://www.youtube.com/watch?v=3qiwOvlIO0w","title":"Sandy — Release Trauma, Stress & Tension (20 Min)"}'::jsonb,
 25, 11),

(12, 'journey_30_grief', 'Grief · 30 min diepe ontlading',
 'Sandy''s 30-minuten journey voor diepe emotionele ontlading — rouw, verdriet, loslaten.',
 'zwaar', 'follow',
 ARRAY['Reserveer 30 min waarin je volledig ongestoord bent','Lig warm en veilig, koptelefoon op','Zakdoekjes bij de hand — dit mag diep gaan']::text[],
 ARRAY['Intro tot ~3:00 — Sandy zet de intentie','Vanaf ~3:00 een lange doorlopende journey op muziek','Ontworpen om verdriet en opgeslagen emotie te laten bewegen','Ruime, stille integratie aan het einde']::text[],
 'Doorlopende verbonden ademhaling, ~27 min, op begeleidende muziek',
 ARRAY['Emotie mag er volledig zijn — huilen, geluid, beweging is welkom','Doe dit alleen als je je stabiel genoeg voelt; anders met begeleiding','Plan rust erna, geen afspraken']::text[],
 'Volg Sandy · 30 min · emotionele ontlading',
 '{"durationMin":30}'::jsonb, '{"requires":[{"type":"sessions","level":11,"count":2}]}'::jsonb, true,
 '{"provider":"youtube","url":"https://www.youtube.com/watch?v=pmSF_2gUoWE","title":"Sandy — GRIEF: 30 Minute Deep Emotional Release"}'::jsonb,
 25, 12),

-- ── ZWAAR / ENDGAME — de diepste journeys ───────────────────────────────────
(13, 'journey_40_rewire', 'Herprogrammeer · 40 min journey',
 'Een 40-minuten journey gericht op je onderbewuste — diep en transformerend.',
 'zwaar', 'follow',
 ARRAY['Alleen doen als de 30-min journey vertrouwd voelt','40 min volledig ongestoord, liggend, warm','Koptelefoon op']::text[],
 ARRAY['Een uitgebreide, doorlopende verbonden ademhaling','De lengte brengt je in diepere, meditatieve staten','Werkt op vastzittende patronen en overtuigingen','Lange integratie in stilte']::text[],
 'Langdurige verbonden ademhaling op muziek, met retenties',
 ARRAY['Bouw op via de kortere journeys — spring hier niet zomaar in','Plan niets voor de rest van je ochtend of avond','Bij twijfel: doe dit met een ervaren begeleider']::text[],
 'Volg Sandy · 40 min · diep',
 '{"durationMin":40}'::jsonb, '{"requires":[{"type":"sessions","level":12,"count":3}]}'::jsonb, true,
 '{"provider":"youtube","url":"https://www.youtube.com/watch?v=0iv__0Kwvzg","title":"Sandy — 40 Minute Journey to Rewire Your Subconscious"}'::jsonb,
 25, 13),

(14, 'journey_45_diep', 'Diepste journey · 45 min',
 'De langste en diepste journey: 45 minuten somatische heling en verruiming.',
 'zwaar', 'follow',
 ARRAY['De top van de leerlijn — alleen als alle kortere journeys vertrouwd zijn','45 min heilige, ongestoorde ruimte, liggend en warm','Koptelefoon op; doe dit bij voorkeur met begeleiding of iemand in de buurt']::text[],
 ARRAY['Een volledige, doorlopende somatische breathwork-journey','45 minuten brengt je in de diepste verruimde staten','Diepe heling, ontlading en integratie','Neem ruim de tijd om terug te komen']::text[],
 'Langdurige, doorlopende verbonden ademhaling op muziek',
 ARRAY['Dit is intens — kom hier pas na maanden opbouw','Nooit alleen doen als je je kwetsbaar voelt','Geef jezelf de rest van de dag rust']::text[],
 'Volg Sandy · 45 min · diepste journey',
 '{"durationMin":45}'::jsonb, '{"requires":[{"type":"sessions","level":13,"count":3}]}'::jsonb, true,
 '{"provider":"youtube","url":"https://www.youtube.com/watch?v=sJ3YzmDiIzA","title":"Sandy — 45 Minute DMT Breathwork Journey (Somatic Healing)"}'::jsonb,
 25, 14);
